### ISSUE TITLE
Redeploying webscript with formatStyle in URI annotation is not effective

### ISSUE THREAD

**Issue by thijslemmens** [laurentvdl/dynamic-extensions-for-alfresco#107]
I tried to update a jar with a webscript without a formatStyle in to one with formatStyle = FormatStyle.ARGUMENT. The change was not effective until I restarted the OSGI container.

**Comment by laurentvdl** [comment]
The url parsing pattern is cached in the Alfresco Webscript cache.
That is why you will still see your extension as part of a UriVariable or vice versa.

The fastest way to resolve this is refreshing the webscript index at /alfresco/service.

Resetting the OSGi container does a lot more then that.
