### ISSUE TITLE
Repository of Dynamic Extensions?

### ISSUE THREAD

**Issue by dhartford** [laurentvdl/dynamic-extensions-for-alfresco#110]
Is there a listing of available Dynamic Extensions?

This is great work, and desperately needed.  On alfresco 4.2.f, having to restart the server just to change the ldap-ad module to add a group...really needs a dynamic extension if there isn't going to be a UI module for it.

**Comment by laurentvdl** [comment]
Alas, not really. I added a placeholder wiki page should anyone like to add a reference: https://github.com/laurentvdl/dynamic-extensions-for-alfresco/wiki/Extension-listing

While configuration management is not the primary use case for DE, it does make it very easy to make ie. dashboards or expose JMX beans.

Alfresco will of course point to the JMX support found in Enterprise.
