### ISSUE TITLE
Webscript Post Parameter

### ISSUE THREAD

**Issue by panzerj** [laurentvdl/dynamic-extensions-for-alfresco#113]
I couldn´t find a way to get @RequestParam work for POST requests. 
Is there a way to pass other types of parameters but URL Variables?

**Comment by laurentvdl** [comment]
For POST requests, you typically submit a JSON body.

When using a (Angular) JS snippet like
```javascript
$http.post("/alfresco/service/mycreateuser", {name: "John"});
```

You would capture that argument with a method like
```java
@Uri(value = "/mycreateuser", method = HttpMethod.POST)
public Resolution createUser(org.json.JSONObject body) {
  String username = body.getString("name");
  ...
}
```
As you can see, no annotation is required for the body parameter. (see https://github.com/laurentvdl/dynamic-extensions-for-alfresco/blob/0382f2cbb15bd68befdf6a992b49fa1ab1d24678/annotations-runtime/src/main/java/com/github/dynamicextensionsalfresco/webscripts/arguments/JsonObjectArgumentResolver.java for implementation)

You should also be able to use @UriVariable: https://github.com/laurentvdl/dynamic-extensions-for-alfresco/wiki/Annotated-WebScripts#urivariable
