### ISSUE TITLE
Share classes between bundles

### ISSUE THREAD

**Issue by cetra3** [laurentvdl/dynamic-extensions-for-alfresco#114]
Wondering if this has been covered already.

I've got an extension bundle which has a few services defined. 
I'm trying to autowire a bean from this bundle from another extension bundle.
I get the generic `Could not autowire field` error message when loading in this second bundle.

Is it possible to autowire a bean from another extension bundle?  Or do I have to convert one into a framework bundle?

**Comment by laurentvdl** [comment]
By default, services are only visible to the extension itself.

If you want to override this, annotate your service with `@OsgiService` on the implementation side.
You can then simply autowire it.

You can see the list of public services via the dashboard: `/alfresco/s/dynamic-extensions/container` and follow the services link.

**Comment by cetra3** [comment]
Ah, excellent stuff.  Is there a wiki/doco where this annotation is listed?

**Comment by laurentvdl** [comment]
There is now: https://github.com/laurentvdl/dynamic-extensions-for-alfresco/wiki/Reusing-Spring-services-or-components
