### ISSUE TITLE
DE module does not start on an alfresco using a read-only Postgres database

### ISSUE THREAD

**Issue by anghelutar** [laurentvdl/dynamic-extensions-for-alfresco#117]
Log here:
https://gist.github.com/anghelutar/2b16423a1585bb786799

**Comment by laurentvdl** [comment]
Give the latest 1.4 snapshot a spin for more tolerant extension bootstrapping: https://github.com/laurentvdl/dynamic-extensions-for-alfresco/releases/tag/1.4.0-SNAPSHOT

PS I recommend handling the exception at the extension level, so your extension can start using readonly access.

**Comment by anghelutar** [comment]
Thanks, I'll try with 1.4.
I'll contact the developer who wrote that ... wait, was that you?

**Comment by anghelutar** [comment]
No luck with 1.4.

**Comment by laurentvdl** [comment]
Actually, no ;)

When you say no luck, you mean Alfresco is not starting anymore ?

**Comment by anghelutar** [comment]
Same error as before. 
Is there a way to know which bundle is responsible for the error? In the logs the ERROR appear when loading DE Itself.

**Comment by laurentvdl** [comment]
It seems the AbstractModuleComponent relies on the RegistryService (which is db/repo based).
Causing retrying transactions (when using a readonly DB) and DE being started twice, which fails at the AbstractModuleComponent level.

I very much welcome a contribution for this.

Option would be to not use use AbstractModuleComponent for starting DE.

**Comment by laurentvdl** [comment]
As suspected, it's a generic ModuleComponent issue.
As a module component is required due to dependencies, the only workaround would be to override RegistryService.addProperty to not abort the transaction or use Alfresco's builtin readonly mode as this allows system writes to the database.
