### ISSUE TITLE
ScheduledQuartzJob changing cron does not work

### ISSUE THREAD

**Issue by thijslemmens** [laurentvdl/dynamic-extensions-for-alfresco#118]
The first deploy always works.
On second deploy, the first cronjob is disable correctly, but the new cron is not active.

Upon restart the new cron becomes active.

Tested on Alfresco One 4.2

**Comment by laurentvdl** [comment]
Tested on Alfresco CE 5.0.d and works as expected: new code becomes active with the new cron interval. (even after deploying several times)

Set the log level for `com.github.dynamicextensionsalfresco.quartz` to debug the issue on your installation.
