### ISSUE TITLE
Not working with Alfresco 5.0 d

### ISSUE THREAD

**Issue by miroslav-beranic** [laurentvdl/dynamic-extensions-for-alfresco#119]
Hi,

is this extension supported on Alfresco Community 5.0.0 d, version Number: 5.0.0 (d r99759-b2). I've downloaded and tested downloadable installation bundle from the Alfresco website.

In Alfresco WAR is see:
alfresco-5.0.d$ java -jar ./bin/alfresco-mmt.jar list ./tomcat/webapps/alfresco.war
Module 'com.github.dynamicextensionsalfresco' installed in './tomcat/webapps/alfresco.war'
   -    Title:        Dynamic Extensions for Alfresco
   -    Version:      1.4.0
   -    Install Date: Wed Sep 30 23:09:05 CEST 2015
   -    Description:   Dynamic Extensions for Alfresco module package

But URL http://localhost:8080/alfresco/service/dynamic-extensions/ gives HTTP 404, also this extension can not be found on webscripts list.

Do you have any idea why this would not work? I use vanilla Alfresco Community download bundle, from https://www.alfresco.com/alfresco-community-download. I am using Ubuntu Linux 14.04 LTS.

**Comment by laurentvdl** [comment]
Hi,

5.0.d is certainly supported. I did a quick check with a vanilla install and DE 1.4 and everything is working as expected.

Are you sure you added the trailing slash to the url? 
http://localhost:8080/alfresco/service/dynamic-extensions/
and not
http://localhost:8080/alfresco/service/dynamic-extensions

You can set the DE log level via the tomcat/webapps/alfresco/WEB-INF/classes/alfresco/module/com.github.dynamicextensionsalfresco/log4j.properties file to DEBUG and then check your alfresco.log file or post it here.
