### ISSUE TITLE
Bootstrapping a bundle without name breaks the dashboard

### ISSUE THREAD

**Issue by stanmine** [laurentvdl/dynamic-extensions-for-alfresco#126]
When Deploying a bundle on the filesystem (/tomcat/webapps/alfresco/WEB-INF/classes/dynamic-extensions/bundles) the dashboard will not load if that bundle has no name.

The expected behaviour is that the dashboard will load.

Stacktrace:
2016-06-17 14:43:12,668  ERROR [extensions.webscripts.AbstractRuntime] [http-apr-8080-exec-2] Exception from executeScript - redirecting to status template error: null
alfresco_1 |  java.lang.NullPointerException
alfresco_1 | 	at com.github.dynamicextensionsalfresco.controlpanel.template.TemplateBundle.compareTo(TemplateBundle.java:185)
alfresco_1 | 	at com.github.dynamicextensionsalfresco.controlpanel.template.TemplateBundle.compareTo(TemplateBundle.java:26)
alfresco_1 | 	at java.util.ComparableTimSort.binarySort(Unknown Source)
alfresco_1 | 	at java.util.ComparableTimSort.sort(Unknown Source)
alfresco_1 | 	at java.util.ComparableTimSort.sort(Unknown Source)
alfresco_1 | 	at java.util.Arrays.sort(Unknown Source)
alfresco_1 | 	at java.util.Collections.sort(Unknown Source)
alfresco_1 | 	at com.github.dynamicextensionsalfresco.controlpanel.Bundles.toTemplateBundles(Bundles.java:122)
alfresco_1 | 	at com.github.dynamicextensionsalfresco.controlpanel.Bundles.index(Bundles.java:37)
alfresco_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
alfresco_1 | 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
alfresco_1 | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
alfresco_1 | 	at java.lang.reflect.Method.invoke(Unknown Source)
alfresco_1 | 	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:186)
alfresco_1 | 	at com.github.dynamicextensionsalfresco.webscripts.AnnotationWebScript.invokeUriHandlerMethod(AnnotationWebScript.java:144)
alfresco_1 | 	at com.github.dynamicextensionsalfresco.webscripts.AnnotationWebScript.execute(AnnotationWebScript.java:66)
alfresco_1 | 	at com.github.dynamicextensionsalfresco.webscripts.WebScriptProxy.execute(WebScriptProxy.java:71)
alfresco_1 | 	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:464)
alfresco_1 | 	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
alfresco_1 | 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:539)
alfresco_1 | 	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:607)
alfresco_1 | 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:381)
alfresco_1 | 	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:262)
alfresco_1 | 	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
alfresco_1 | 	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
alfresco_1 | 	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
alfresco_1 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
alfresco_1 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
alfresco_1 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
alfresco_1 | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
alfresco_1 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
alfresco_1 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
alfresco_1 | 	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
alfresco_1 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
alfresco_1 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
alfresco_1 | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
alfresco_1 | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
alfresco_1 | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
alfresco_1 | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
alfresco_1 | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
alfresco_1 | 	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
alfresco_1 | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
alfresco_1 | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
alfresco_1 | 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
alfresco_1 | 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
alfresco_1 | 	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2403)
alfresco_1 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
alfresco_1 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
alfresco_1 | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
alfresco_1 | 	at java.lang.Thread.run(Unknown Source)

**Comment by laurentvdl** [comment]
It would seems you are deploying a regular jar file via the classpath: a jar with no osgi manifest, so not a bundle.

The behaviour for classpath bundles is different then for repository bundles: repo bundles are transformed if required to osgi bundles before being stored in the repository.
As classpath bundles can only be read, not written, this is not possible for those bundles/jar files.

As a workaround, you can follow the instructions at https://github.com/laurentvdl/dynamic-extensions-for-alfresco/wiki/Extension-dependencies to alter the jar file before deployment.

In case you're having issues with regular bundles, please provide an example.

**Comment by laurentvdl** [comment]
try the current master branch
