### ISSUE TITLE
Dynamic JavaScript Root Object?

### ISSUE THREAD

**Issue by wildloop** [laurentvdl/dynamic-extensions-for-alfresco#127]
In traditional way we can define the new JS root object using bean definition:

```
<bean id="myBean" class="mypackage.MyRootClass" parent="baseJavaScriptExtension">
    <property name="extensionName" value="myRootObj"/>
    <property name="serviceRegistry" ref="ServiceRegistry" />
</bean>
```

and Java class:

```
public class MyRootClass extends BaseScopableProcessorExtension {
    protected ServiceRegistry serviceRegistry = null;
    public void setServiceRegistry(ServiceRegistry serviceRegistry) {
        this.serviceRegistry = serviceRegistry;
    }
    public String doSomething(){
       return "test";
    }
}

```

Can we implement this as dynamic extension?

**Comment by laurentvdl** [comment]
Not out of the box.

Looking at the BaseScopableProcessorExtension, it would appear you can simply register your JS extensions via the `javaScriptProcessor` bean using the Processor.registerProcessorExtension method.
(use @PostConstruct to initialize a bean)

However, like most Alfresco API's there is no unregister functionality. Meaning you will get a memory leak when undeploying your extension.

Registering a new version will replace the previous implementation, avoiding a leak. So not a huge problem.
